### ISSUE TITLE
how can i view all defined route?

### ISSUE THREAD

**Issue by ngangchill** [Patroklo/codeigniter-static-laravel-routes#10]
how can i view all defined route?

**Comment by Patroklo** [comment]
Hi, do you mean viewing all the routes you have implemented in your code? 
If that, that's impossible, the engine only renders the useful routes, for example, if you make a post call, only the "any" and "post" will be rendered.

**Comment by ngangchill** [comment]
thanx for replay...

in laravel, there is a scope to view all active routes... 

I made a rough one for my purpose to see all active routes.

thanx for the great library...
