### ISSUE TITLE
HMVC: how to put routes file in different modules folder

### ISSUE THREAD

**Issue by ngangchill** [Patroklo/codeigniter-static-laravel-routes#16]
im using wiredesignz Modular extensions - HMVC . i want to put routes file in its own module rather than application/routes folder.

modules
       >> example
            >> controllers
                >> Example.php
            >> routes
                >> example.php
            >> views
               >> some_view_files

**Comment by afbora** [comment]
HMVC already have module routes feature . For example:

```
/application/modules/blog/config/routes.php
```

**Comment by ngangchill** [comment]
Ohh! thanks

**Comment by ngangchill** [comment]
i want to define my routes using this library not by ci default routes..sow can i do that????

**Comment by afbora** [comment]
Like that:

> /application/modules/blog/config/routes.php

```
$route['(blog)']                        = 'blog/index';
$route['(blog)/(:num)/(:num)/(:any)']   = 'blog/view/$4';
$route['(blog)/page(/:num)?']           = 'blog/index$2';

$route = Route::map($route);
```

**Comment by ngangchill** [comment]
Thanks for replay.. i got it but

i want this route like

Route::any('blog', 'blog/index');
Route::any('blog/page/{id}', 'blog/page/$1');

???

**Comment by afbora** [comment]
And you should write end:

```
$route = Route::map();
```

**Comment by ngangchill** [comment]
tried but no luck..  :cry:

**Comment by Patroklo** [comment]
> Important note: the Route::map() call method must be always placed only at the "/application/config/routes.php" file.

I think that you should only use the map method in the main route file (if it's called, I can't quite remember how HMVC works).

**Comment by ngangchill** [comment]
it sounds good without complication to me.
thanks @Patroklo
