### ISSUE TITLE
Keep all function with no route defined

### ISSUE THREAD

**Issue by dhha** [Patroklo/codeigniter-static-laravel-routes#17]
I have a CI project and now i want to implement this library into it. but seem like it blocks all functions that i did not define in route file.

Please give me advise, How can i keep them? thanks

**Comment by Ihabafia** [comment]
As far as i know,  you have to incloude every route to the routes file. Otherwise if you have a wild route then the purpose of the library will be gone.

**Comment by Patroklo** [comment]
Hi
Yes, you have to add all the routes or at least use wildcards to include in them all the routes. It's a better system at long term for you and your applications.

**Comment by dhha** [comment]
Hi,
Thanks for all response, is there any way to list out all of them? cos my project is quite big then it hard to do by manual

**Comment by Patroklo** [comment]
You could add wildcards like `photo/(:any)/(:any)/(:any)/(:any)/(:any)/(:any)       $1/photo/$2/$3/$4/$5/$6` for example. Don't know if I have explained myself in that...

**Comment by dhha** [comment]
I found out solution

foreach(glob(APPPATH . 'controllers/*'.'.php') as $controller)
{
    $controller = basename($controller, '.php');
    $route[$controller] = $controller . '/index';
    $route[$controller . '/(.+)'] = $controller . '/$1';
}

Thank all.
