### ISSUE TITLE
MY_Router::_set_routing include any file in routes/

### ISSUE THREAD

**Issue by xenogenesi** [Patroklo/codeigniter-static-laravel-routes#3]
I've an empty `routes/` directory with `index.html` only (directory access restricted) and it was included.

I added something like the code below in the `foreach` loop.

```
if (pathinfo($file, PATHINFO_EXTENSION) !== 'php') {
    continue;
}
```

**Comment by Patroklo** [comment]
Yeah, you are right, i have never used this library with index.html files in the directory. If you want make the change and I'll add it into the library, if not, tell me and I'll handle it

**Comment by xenogenesi** [comment]
Please handle it, I'll update the checkout.

**Comment by Patroklo** [comment]
Ok, right now I have serious back ache problems, the moment I can sit down some time in the computer without severe pain I'll fix it.

**Comment by Patroklo** [comment]
Ok, done, you can checkout!

**Comment by xenogenesi** [comment]
Perfect, thanks.

**Comment by Patroklo** [comment]
ill reopen in case there is any problem, ill close it in some days if nothing happens, thanks!

**Comment by xenogenesi** [comment]
I'll use it in the next few days, eventually will let you know. Thanks again.
