### ISSUE TITLE
accessing the js and css folders

### ISSUE THREAD

**Issue by Ihabafia** [Patroklo/codeigniter-static-laravel-routes#5]
I can't access the css and js assets folder because of the routing problem, how could I solve that?

domain.dev/_assets/css/common/select2.min.css

when I access it through the browser it's giving file not fount.

which they are on the folder /application/_assets/css/common/select2.min.css

Thank you,

**Comment by laynebay** [comment]
How are you referencing the asset files? Using `<base_url()>`? Ive usually seen this problem due to .htaccess configuration, but haven't experienced it with static routes.  I'm also using HMVC.

**Comment by Ihabafia** [comment]
I am having the _assets folder inside the application folder.

**Comment by Ihabafia** [comment]
I am sorry, it's my fault, I suppose to put the _assets folder outside the application folder, and now it's working fine.

Thank you,
