### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by Ihabafia** [Patroklo/codeigniter-static-laravel-routes#6]
Hi,

I would like to use the filter function in the routes/my_route.php

like: 

Route::filter('logged_in', function(){
    if($this->auth->logged_in() == FALSE)
    {
        show_404();
    }
});

Route::get('auth', 'auth/index', array('before' => 'logged_in'));

The problem is that the library and the model of the ion_auth was not loaded yet, so it's giving an error for that, even when I tried to use the session variable it's giving the same error:

Route::filter('logged_in', function(){
    if(!$this->session->userdata('user_id'))
    {
        show_404();
    }
});

the error looks like this:

A PHP Error was encountered
Severity: Notice
Message: Undefined property: MY_Router::$my_auth
Filename: routes/my_routes.php
Line Number: 17

Backtrace:
File: /Users/ehabafia/Dropbox/WebProjects/ci3/application/routes/my_routes.php
Line: 17
Function: _error_handler

File: /Users/ehabafia/Dropbox/WebProjects/ci3/application/core/MY_Controller.php
Line: 88
Function: call_user_func_array

File: /Users/ehabafia/Dropbox/WebProjects/ci3/application/core/MY_Controller.php
Line: 15
Function: call_filters

File: /Users/ehabafia/Dropbox/WebProjects/ci3/application/modules/auth/controllers/Auth.php
Line: 6
Function: __construct

File: /Users/ehabafia/Dropbox/WebProjects/ci3/index.php
Line: 319
Function: require_once

Fatal error: Call to a member function logged_in() on a non-object in /Users/ehabafia/Dropbox/WebProjects/ci3/application/routes/my_routes.php on line 17

Please advise me.

Thank you,

**Comment by Patroklo** [comment]
Something seems to have changed in the past months, $this works now as a MY_Router extension, so no $this->load.
You can use $ci =& get_instance(); though

**Comment by Patroklo** [comment]
Ok, I have found a workaround, now I have to check for problems that it could have.

**Comment by Patroklo** [comment]
Won't you have php 5.3 installed by the way? that would be awesome to check the change...

**Comment by Ihabafia** [comment]
My PHP is 5.5.23

**Comment by Patroklo** [comment]
Made a upgrade at MY_Controller, try that, it should work right now. Only for php >= 5.4 . Php 5.3 doesn't even have $this on closures, so won't be a problem.

**Comment by Ihabafia** [comment]
It works fine for now,

But the problem I have the filter:

Route::filter('logged_in', function(){
    if($this->my_auth->logged_in() == FALSE)
    {
        echo "Not logged in !!!";exit;
    } else {
        echo "You are looged in :)"; exit;
    }
});

Route::get('auth', 'auth/index', array('before' => 'logged_in'));

when I go to domain.dev/auth it does the test and the filter works, but if I go to:

domain.dev/      only, it passes the test and it execute the Auth Controller class without the filter. Keep in mind that I have this route as a default.

$route = Route::map();

$route['default_controller'] = 'auth';

in the routes.php

Any advise?

**Comment by Patroklo** [comment]
Filter only applies at the routes defined with that, also must have MY_Controller as parent. I think Auth doesn't apply any of this.

**Comment by Ihabafia** [comment]
No, I made Auth working for now, but it seem to be that the default controller can't be filtered :(

**Comment by Patroklo** [comment]
Lol, yes, with this, just found out:

Route::any('default_controller', 'Welcome/dorp', array('before' => 'logged_in'));
Route::any('', 'Welcome/dorp', array('before' => 'logged_in'));

**Comment by Ihabafia** [comment]
So, do I remove the default_controller, or I keep both?

**Comment by Patroklo** [comment]
Yes you can, doing a default_controller for the routing and another with an empty string for the filtering.

**Comment by Patroklo** [comment]
It's a bug. Don't know how to modify it right now, I'll think about it.

**Comment by Patroklo** [comment]
Try the new MY_Route, should fix the problem.

**Comment by Patroklo** [comment]
If you can check this please tell me if it works for you.

**Comment by Ihabafia** [comment]
what should I do to check it ?

**Comment by Ihabafia** [comment]
## Great Work

**Comment by Ihabafia** [comment]
I am sorry, what I did now is the following:

$route = Route::map();

$route['default_controller'] = 'home';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;

Route::get('home', 'home/index', ['before' => 'logged_in']);

That's it, this way, if I go to domain.dev and I am not logged in it still go.

Do I need to add this:

Route::any('default_controller', 'home/index', array('before' => 'logged_in'));
 ?

Please advise:

**Comment by Patroklo** [comment]
Mine works fine like this:

Route::any('default_controller', 'Welcome/index', array('before' => 'logged_in'));
$route = Route::map();
//$route['default_controller'] = 'Welcome';

**Comment by Ihabafia** [comment]
I think, it's because I was having default_controller after Route::map();.

It works, thank you,
