### ISSUE TITLE
PUT and DELETE

### ISSUE THREAD

**Issue by Ihabafia** [Patroklo/codeigniter-static-laravel-routes#7]
Hi,

As you know $_SERVER['REQUEST_METHOD'] doesn't support PUT and DELETE, it supports GET and POST only,  I saw on another library the following hack and I use to use this library perfectly except that it's missing allot of your library.

class MY_Router extends MX_Router {

```
function __construct()
{
    // HACK: support overridding REQUEST_METHOD by posting a _method parameter
    if($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['_method']))
    {
        $_SERVER['REQUEST_METHOD'] = strtoupper($_POST['_method']);
    }
    elseif(isset($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']))
    {
        $_SERVER['REQUEST_METHOD'] = strtoupper($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE']);
    }

    parent::__construct();
}
```

Because they are extending the MX_Router he got a __construct() and he got that hack which is basically you add a hidden field in the form called "_method" and you make the value "PUT" or "DELETE", that way the hack will make the $_SERVER("REQUEST_METHOD") to be "PUT or DELETE".

So can you add this to your library or you have another solution on yours.

Thank you,

**Comment by Ihabafia** [comment]
Did you saw that post.

Thank you,

**Comment by Patroklo** [comment]
The thing is that's not always true. You can be using a webservice server library and it will work very differently. The "PUT", "DELETE" and special calls management should be worked out by the developer, not this library, because each case is totaly different and I cant cover them all.
